// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static CreouDotCom.Controllers.ContactController Contact = new CreouDotCom.Controllers.T4MVC_ContactController();
    public static CreouDotCom.Controllers.HomeController Home = new CreouDotCom.Controllers.T4MVC_HomeController();
    public static CreouDotCom.Controllers.ProjectsController Projects = new CreouDotCom.Controllers.T4MVC_ProjectsController();
    public static T4MVC.BlogController Blog = new T4MVC.BlogController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class scripts {
        private const string URLPATH = "~/scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string jquery_1_9_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.9.1.min.js") ? Url("jquery-1.9.1.min.js") : Url("jquery-1.9.1.js");
        public static readonly string jquery_1_9_1_min_js = Url("jquery-1.9.1.min.js");
        public static readonly string jquery_2_1_1_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.1.1.intellisense.min.js") ? Url("jquery-2.1.1.intellisense.min.js") : Url("jquery-2.1.1.intellisense.js");
        public static readonly string jquery_2_1_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.1.1.min.js") ? Url("jquery-2.1.1.min.js") : Url("jquery-2.1.1.js");
        public static readonly string jquery_2_1_1_min_js = Url("jquery-2.1.1.min.js");
        public static readonly string jquery_2_1_1_min_map = Url("jquery-2.1.1.min.map");
        public static readonly string jquery_ui_1_10_2_min_js = Url("jquery-ui-1.10.2.min.js");
        public static readonly string jquery_ui_1_11_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.11.2.min.js") ? Url("jquery-ui-1.11.2.min.js") : Url("jquery-ui-1.11.2.js");
        public static readonly string jquery_ui_1_11_2_min_js = Url("jquery-ui-1.11.2.min.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string knockout_2_2_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout-2.2.1.min.js") ? Url("knockout-2.2.1.min.js") : Url("knockout-2.2.1.js");
        public static readonly string knockout_2_2_1_min_js = Url("knockout-2.2.1.min.js");
        public static readonly string modernizr_2_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.8.3.min.js") ? Url("modernizr-2.8.3.min.js") : Url("modernizr-2.8.3.js");
        public static readonly string modernizr_2_min_js = Url("modernizr-2.min.js");
        public static readonly string npm_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/npm.min.js") ? Url("npm.min.js") : Url("npm.js");
        public static readonly string tech_match_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tech-match.min.js") ? Url("tech-match.min.js") : Url("tech-match.js");
        public static readonly string underscore_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/underscore.min.js") ? Url("underscore.min.js") : Url("underscore.js");
        public static readonly string underscore_min_js = Url("underscore.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class content {
        private const string URLPATH = "~/content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class blog {
            private const string URLPATH = "~/content/blog";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string cssrolloverbutton_html = Url("cssrolloverbutton.html");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class cssrolloverbutton_files {
                private const string URLPATH = "~/content/blog/cssrolloverbutton_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string example_png = Url("example.png");
            }
        
            public static readonly string extostring_html = Url("extostring.html");
            public static readonly string fizzbuzzincss_html = Url("fizzbuzzincss.html");
            public static readonly string globalgamesjam_html = Url("globalgamesjam.html");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class globalgamesjam_files {
                private const string URLPATH = "~/content/blog/globalgamesjam_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string AnotherSample_jpg = Url("AnotherSample.jpg");
                public static readonly string CIMG3539_JPG = Url("CIMG3539.JPG");
                public static readonly string CIMG3539s_jpg = Url("CIMG3539s.jpg");
                public static readonly string CIMG3540_JPG = Url("CIMG3540.JPG");
                public static readonly string CIMG3540s_jpg = Url("CIMG3540s.jpg");
                public static readonly string CIMG3541_JPG = Url("CIMG3541.JPG");
                public static readonly string CIMG3541s_jpg = Url("CIMG3541s.jpg");
                public static readonly string CIMG3555s_jpg = Url("CIMG3555s.jpg");
                public static readonly string CIMG3558s_jpg = Url("CIMG3558s.jpg");
                public static readonly string CIMG3568s_jpg = Url("CIMG3568s.jpg");
                public static readonly string FullTerrain_jpg = Url("FullTerrain.jpg");
                public static readonly string Ouroboros_preview_jpg = Url("Ouroboros.preview.jpg");
                public static readonly string Ouroboros_preview_png = Url("Ouroboros.preview.png");
                public static readonly string preview1_jpg = Url("preview1.jpg");
                public static readonly string skitz_jpg = Url("skitz.jpg");
                public static readonly string Team_jpg = Url("Team.jpg");
                public static readonly string TerrainBad_jpg = Url("TerrainBad.jpg");
                public static readonly string TerrainGood_jpg = Url("TerrainGood.jpg");
                public static readonly string WithLights_jpg = Url("WithLights.jpg");
            }
        
            public static readonly string ie9roundedgradient_html = Url("ie9roundedgradient.html");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class ie9roundedgradient_files {
                private const string URLPATH = "~/content/blog/ie9roundedgradient_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string example_png = Url("example.png");
            }
        
            public static readonly string microsoft_locked_down_html = Url("microsoft-locked-down.html");
            public static readonly string nokialumia800_html = Url("nokialumia800.html");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class nokialumia800_Files {
                private const string URLPATH = "~/content/blog/nokialumia800_Files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string cimg2773_JPG = Url("cimg2773.JPG");
                public static readonly string cimg2776_JPG = Url("cimg2776.JPG");
                public static readonly string cimg2777_JPG = Url("cimg2777.JPG");
                public static readonly string cimg2779_JPG = Url("cimg2779.JPG");
                public static readonly string cimg2786_JPG = Url("cimg2786.JPG");
                public static readonly string cimg2787_JPG = Url("cimg2787.JPG");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class oneweekgame_day1_files {
                private const string URLPATH = "~/content/blog/oneweekgame-day1_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string demo1_wmv = Url("demo1.wmv");
                public static readonly string preview_jpg = Url("preview.jpg");
                public static readonly string screenshot1_jpg = Url("screenshot1.jpg");
                public static readonly string screenshot2_jpg = Url("screenshot2.jpg");
                public static readonly string sketch1_jpg = Url("sketch1.jpg");
                public static readonly string sketch2_jpg = Url("sketch2.jpg");
                public static readonly string sketch3_jpg = Url("sketch3.jpg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class oneweekgame_day2_files {
                private const string URLPATH = "~/content/blog/oneweekgame-day2_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string demo1_wmv = Url("demo1.wmv");
                public static readonly string preview_jpg = Url("preview.jpg");
                public static readonly string screenshot1_jpg = Url("screenshot1.jpg");
                public static readonly string screenshot2_jpg = Url("screenshot2.jpg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class oneweekgame_day3_files {
                private const string URLPATH = "~/content/blog/oneweekgame-day3_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string preview_jpg = Url("preview.jpg");
                public static readonly string screenshot1_jpg = Url("screenshot1.jpg");
                public static readonly string screenshot2_jpg = Url("screenshot2.jpg");
                public static readonly string screenshot3_after_jpg = Url("screenshot3_after.jpg");
                public static readonly string screenshot3_before_jpg = Url("screenshot3_before.jpg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class oneweekgame_day4_files {
                private const string URLPATH = "~/content/blog/oneweekgame-day4_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string preview_jpg = Url("preview.jpg");
                public static readonly string screenshot1_jpg = Url("screenshot1.jpg");
                public static readonly string screenshot2_jpg = Url("screenshot2.jpg");
                public static readonly string screenshot3_jpg = Url("screenshot3.jpg");
                public static readonly string screenshot4_jpg = Url("screenshot4.jpg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class oneweekgame_day5_files {
                private const string URLPATH = "~/content/blog/oneweekgame-day5_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string preview_jpg = Url("preview.jpg");
                public static readonly string screenshot1_jpg = Url("screenshot1.jpg");
                public static readonly string screenshot2_jpg = Url("screenshot2.jpg");
                public static readonly string tiles_jpg = Url("tiles.jpg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class oneweekgame_day6_files {
                private const string URLPATH = "~/content/blog/oneweekgame-day6_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string _3DModel_jpg = Url("3DModel.jpg");
                public static readonly string preview_jpg = Url("preview.jpg");
                public static readonly string puzzle_jpg = Url("puzzle.jpg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class oneweekgame_day7_files {
                private const string URLPATH = "~/content/blog/oneweekgame-day7_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Level1_jpg = Url("Level1.jpg");
                public static readonly string Level2_jpg = Url("Level2.jpg");
                public static readonly string Level3_jpg = Url("Level3.jpg");
                public static readonly string Level4_jpg = Url("Level4.jpg");
                public static readonly string Level5_jpg = Url("Level5.jpg");
                public static readonly string Level6_jpg = Url("Level6.jpg");
                public static readonly string Level7_jpg = Url("Level7.jpg");
                public static readonly string Level8_jpg = Url("Level8.jpg");
                public static readonly string preview_jpg = Url("preview.jpg");
                public static readonly string title_jpg = Url("title.jpg");
            }
        
            public static readonly string oneweekgame_html = Url("oneweekgame.html");
            public static readonly string oneweekgame_day1_html = Url("oneweekgame_day1.html");
            public static readonly string oneweekgame_day2_html = Url("oneweekgame_day2.html");
            public static readonly string oneweekgame_day3_html = Url("oneweekgame_day3.html");
            public static readonly string oneweekgame_day4_html = Url("oneweekgame_day4.html");
            public static readonly string oneweekgame_day5_html = Url("oneweekgame_day5.html");
            public static readonly string oneweekgame_day6_html = Url("oneweekgame_day6.html");
            public static readonly string oneweekgame_day7_html = Url("oneweekgame_day7.html");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class oneweekgame_files {
                private const string URLPATH = "~/content/blog/oneweekgame_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string screenshot1_jpg = Url("screenshot1.jpg");
                public static readonly string title_jpg = Url("title.jpg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class python_cheat_sheet_files {
                private const string URLPATH = "~/content/blog/python-cheat-sheet_files";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string PythonGuide_odt = Url("PythonGuide.odt");
                public static readonly string PythonGuide_pdf = Url("PythonGuide.pdf");
                public static readonly string PythonGuide_png = Url("PythonGuide.png");
            }
        
            public static readonly string pythoncheatsheet_html = Url("pythoncheatsheet.html");
            public static readonly string wp8soaphttpheaders_html = Url("wp8soaphttpheaders.html");
        }
    
        public static readonly string blueprint_png = Url("blueprint.png");
        public static readonly string bug_png = Url("bug.png");
        public static readonly string cog_png = Url("cog.png");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class contact {
            private const string URLPATH = "~/content/contact";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string CodeProjectLogo_png = Url("CodeProjectLogo.png");
            public static readonly string CodeProjectLogoSmall_png = Url("CodeProjectLogoSmall.png");
            public static readonly string FacebookLogo_png = Url("FacebookLogo.png");
            public static readonly string FacebookLogoSmall_png = Url("FacebookLogoSmall.png");
            public static readonly string GithubLogo_png = Url("GithubLogo.png");
            public static readonly string GithubLogoSmall_png = Url("GithubLogoSmall.png");
            public static readonly string GooglePlusLogo_png = Url("GooglePlusLogo.png");
            public static readonly string GooglePlusLogoSmall_png = Url("GooglePlusLogoSmall.png");
            public static readonly string HackerNewsLogo_png = Url("HackerNewsLogo.png");
            public static readonly string HackerNewsLogoSmall_png = Url("HackerNewsLogoSmall.png");
            public static readonly string LinkedInLogo_png = Url("LinkedInLogo.png");
            public static readonly string LinkedInLogoSmall_png = Url("LinkedInLogoSmall.png");
            public static readonly string NxtGenLogo_png = Url("NxtGenLogo.png");
            public static readonly string NxtGenLogoSmall_png = Url("NxtGenLogoSmall.png");
            public static readonly string StackOverflowLogo_png = Url("StackOverflowLogo.png");
            public static readonly string StackOverflowLogoSmall_png = Url("StackOverflowLogoSmall.png");
            public static readonly string TwitterLogo_png = Url("TwitterLogo.png");
            public static readonly string TwitterLogoSmall_png = Url("TwitterLogoSmall.png");
            public static readonly string XNAUKLogo_png = Url("XNAUKLogo.png");
            public static readonly string XNAUKLogoSmall_png = Url("XNAUKLogoSmall.png");
        }
    
        public static readonly string CreouTextLogo_Black_png = Url("CreouTextLogo_Black.png");
        public static readonly string CreouTextLogo_Black_Fade_png = Url("CreouTextLogo_Black_Fade.png");
        public static readonly string CreouTextLogo_xs_png = Url("CreouTextLogo_xs.png");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class cv {
            private const string URLPATH = "~/content/cv";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        }
    
        public static readonly string data1_png = Url("data1.png");
        public static readonly string data2_png = Url("data2.png");
        public static readonly string data3_png = Url("data3.png");
        public static readonly string header_chrome_jpg = Url("header-chrome.jpg");
        public static readonly string man_png = Url("man.png");
        public static readonly string side_chrome_jpg = Url("side-chrome.jpg");
        public static readonly string sps_jpg = Url("sps.jpg");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/accordion.min.css") ? Url("accordion.min.css") : Url("accordion.css");
                     
                public static readonly string all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/all.min.css") ? Url("all.min.css") : Url("all.css");
                     
                public static readonly string autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autocomplete.min.css") ? Url("autocomplete.min.css") : Url("autocomplete.css");
                     
                public static readonly string base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/base.min.css") ? Url("base.min.css") : Url("base.css");
                     
                public static readonly string button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/button.min.css") ? Url("button.min.css") : Url("button.css");
                     
                public static readonly string core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/core.min.css") ? Url("core.min.css") : Url("core.css");
                     
                public static readonly string datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/datepicker.min.css") ? Url("datepicker.min.css") : Url("datepicker.css");
                     
                public static readonly string dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dialog.min.css") ? Url("dialog.min.css") : Url("dialog.css");
                     
                public static readonly string draggable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/draggable.min.css") ? Url("draggable.min.css") : Url("draggable.css");
                     
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/menu.min.css") ? Url("menu.min.css") : Url("menu.css");
                     
                public static readonly string progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/progressbar.min.css") ? Url("progressbar.min.css") : Url("progressbar.css");
                     
                public static readonly string resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/resizable.min.css") ? Url("resizable.min.css") : Url("resizable.css");
                     
                public static readonly string selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/selectable.min.css") ? Url("selectable.min.css") : Url("selectable.css");
                     
                public static readonly string selectmenu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/selectmenu.min.css") ? Url("selectmenu.min.css") : Url("selectmenu.css");
                     
                public static readonly string slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/slider.min.css") ? Url("slider.min.css") : Url("slider.css");
                     
                public static readonly string sortable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/sortable.min.css") ? Url("sortable.min.css") : Url("sortable.css");
                     
                public static readonly string spinner_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/spinner.min.css") ? Url("spinner.min.css") : Url("spinner.css");
                     
                public static readonly string tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tabs.min.css") ? Url("tabs.min.css") : Url("tabs.css");
                     
                public static readonly string theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/theme.min.css") ? Url("theme.min.css") : Url("theme.css");
                     
                public static readonly string tooltip_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/tooltip.min.css") ? Url("tooltip.min.css") : Url("tooltip.css");
                     
            }
        
        }
    
        public static readonly string trans_pixel_b_png = Url("trans_pixel_b.png");
        public static readonly string trans_pixel_w_png = Url("trans_pixel_w.png");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009


